<a href="https://colab.research.google.com/github/rafastos/atividadesIA/blob/main/IA_Exerc%C3%ADcio_08_Rede_Neural_Artificial_Python_SkLearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Treinamento

### Carregando Arquivo de Treinamento (.csv)

In [113]:
import pandas as pd
# Carregando dados do arquivo CSV
url = 'https://raw.githubusercontent.com/rafastos/atividadesIA/refs/heads/main/diabetes_treinamento.csv'
base_Treinamento = pd.read_csv(url,sep=',', encoding = 'UTF-8').values
print("---------------------------------")
print("Dados dos Pacientes - TREINAMENTO")
print("---------------------------------")
print(base_Treinamento)
print("---------------------------------")

# Extração dos Atributos a serem utilizadas pela rede
print("Atributos de Entrada")
print("---------------------------------")
print(base_Treinamento[:, 0:8])

print("----------------------------")
print("Classificação Supervisionada")
print("----------------------------")
print(base_Treinamento[:, -1])

---------------------------------
Dados dos Pacientes - TREINAMENTO
---------------------------------
[[6.000e+00 1.480e+02 7.200e+01 ... 6.270e-01 5.000e+01 1.000e+00]
 [1.000e+00 8.500e+01 6.600e+01 ... 3.510e-01 3.100e+01 0.000e+00]
 [8.000e+00 1.830e+02 6.400e+01 ... 6.720e-01 3.200e+01 1.000e+00]
 ...
 [4.000e+00 1.970e+02 7.000e+01 ... 2.329e+00 3.100e+01 0.000e+00]
 [0.000e+00 1.170e+02 8.000e+01 ... 8.900e-02 2.400e+01 0.000e+00]
 [4.000e+00 1.420e+02 8.600e+01 ... 6.450e-01 2.200e+01 1.000e+00]]
---------------------------------
Atributos de Entrada
---------------------------------
[[6.000e+00 1.480e+02 7.200e+01 ... 3.360e+01 6.270e-01 5.000e+01]
 [1.000e+00 8.500e+01 6.600e+01 ... 2.660e+01 3.510e-01 3.100e+01]
 [8.000e+00 1.830e+02 6.400e+01 ... 2.330e+01 6.720e-01 3.200e+01]
 ...
 [4.000e+00 1.970e+02 7.000e+01 ... 3.670e+01 2.329e+00 3.100e+01]
 [0.000e+00 1.170e+02 8.000e+01 ... 4.520e+01 8.900e-02 2.400e+01]
 [4.000e+00 1.420e+02 8.600e+01 ... 4.400e+01 6.450e-01 2.200

### Pré-processamento de Dados

In [114]:
import numpy as np
from sklearn import preprocessing

print(np.unique(base_Treinamento[:, -1]))

#Concatenação de Atributos (Colunas)
atributos_norm = base_Treinamento[:, 0:8]
print("--------------------------------")
print("Atributos de Entrada - Numéricos")
print("--------------------------------")
print(atributos_norm)

print("----------------------------------------")
print("Classificação Supervisionada - Numéricos")
print("----------------------------------------")
diagnostico_norm = base_Treinamento[:, -1]
print(diagnostico_norm)

[0. 1.]
--------------------------------
Atributos de Entrada - Numéricos
--------------------------------
[[6.000e+00 1.480e+02 7.200e+01 ... 3.360e+01 6.270e-01 5.000e+01]
 [1.000e+00 8.500e+01 6.600e+01 ... 2.660e+01 3.510e-01 3.100e+01]
 [8.000e+00 1.830e+02 6.400e+01 ... 2.330e+01 6.720e-01 3.200e+01]
 ...
 [4.000e+00 1.970e+02 7.000e+01 ... 3.670e+01 2.329e+00 3.100e+01]
 [0.000e+00 1.170e+02 8.000e+01 ... 4.520e+01 8.900e-02 2.400e+01]
 [4.000e+00 1.420e+02 8.600e+01 ... 4.400e+01 6.450e-01 2.200e+01]]
----------------------------------------
Classificação Supervisionada - Numéricos
----------------------------------------
[1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1.
 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 1. 0. 0.
 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0.
 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0.
 0. 0. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 1. 0. 0. 1. 0. 0. 1. 1. 

### Treinamento do Neurônio Perceptron

In [115]:
from sklearn.linear_model import Perceptron
# Treinamento do Perceptron a partir dos atributos de entrada e classificações
modelo = Perceptron()
modelo.fit(atributos_norm, diagnostico_norm)

# Acurácia do modelo, que é : 1 - (predições erradas / total de predições)
# Acurácia do modelo: indica uma performance geral do modelo.
# Dentre todas as classificações, quantas o modelo classificou corretamente;
# (VP+VN)/N
print('Acurácia: %.3f' % modelo.score(atributos_norm, diagnostico_norm))

Acurácia: 0.591


### ----------------------------------------------------------------------------

# Validação do Aprendizado

### Predição Simples

In [116]:
linha769 = [[1,93,70,31,0,30.4,0.315,23]]
print("Linha 769", modelo.predict(linha769), "Esperado: 0")
linha677 = [[6,195,70,0,0,30.9,0.328,31]]
print("Linha 677", modelo.predict(linha677), "Esperado: 1")

Linha 769 [0.] Esperado: 0
Linha 677 [0.] Esperado: 1


### Predição a partir de base de dados (.csv)

In [117]:
import pandas as pd
# Carregando dados do arquivo CSV
url = 'https://raw.githubusercontent.com/rafastos/atividadesIA/refs/heads/main/diabetes.csv'
base_Testes = pd.read_csv(url,sep=',', encoding = 'UTF-8').values
print("----------------------------")
print("Dados dos Pacientes - TESTES")
print("----------------------------")
print(base_Testes)
print("---------------------------------")

# Extração dos Atributos a serem utilizadas pela rede
print("Atributos de Entrada")
print("---------------------------------")
print(base_Testes[:, 0:8])

----------------------------
Dados dos Pacientes - TESTES
----------------------------
[[  6.    148.     72.    ...   0.627  50.      1.   ]
 [  1.     85.     66.    ...   0.351  31.      0.   ]
 [  8.    183.     64.    ...   0.672  32.      1.   ]
 ...
 [  5.    121.     72.    ...   0.245  30.      0.   ]
 [  1.    126.     60.    ...   0.349  47.      1.   ]
 [  1.     93.     70.    ...   0.315  23.      0.   ]]
---------------------------------
Atributos de Entrada
---------------------------------
[[  6.    148.     72.    ...  33.6     0.627  50.   ]
 [  1.     85.     66.    ...  26.6     0.351  31.   ]
 [  8.    183.     64.    ...  23.3     0.672  32.   ]
 ...
 [  5.    121.     72.    ...  26.2     0.245  30.   ]
 [  1.    126.     60.    ...  30.1     0.349  47.   ]
 [  1.     93.     70.    ...  30.4     0.315  23.   ]]


### Pré-processamento de Dados

In [118]:
import numpy as np
from sklearn import preprocessing

print(np.unique(base_Testes[:, -1]))

print("--------------------------------")
print("Atributos de Entrada - Numéricos")
print("--------------------------------")
atributos_teste = base_Testes[:, 0:8]
print(atributos_teste)

[0. 1.]
--------------------------------
Atributos de Entrada - Numéricos
--------------------------------
[[  6.    148.     72.    ...  33.6     0.627  50.   ]
 [  1.     85.     66.    ...  26.6     0.351  31.   ]
 [  8.    183.     64.    ...  23.3     0.672  32.   ]
 ...
 [  5.    121.     72.    ...  26.2     0.245  30.   ]
 [  1.    126.     60.    ...  30.1     0.349  47.   ]
 [  1.     93.     70.    ...  30.4     0.315  23.   ]]


### Predição da Base

In [119]:
base_Predicao = modelo.predict((atributos_teste))
print("Classificações: ", base_Predicao)

Classificações:  [0. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 0. 0. 1. 1. 1. 1. 0. 1. 0. 1. 0. 0. 0.
 0. 1. 0. 1. 1. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0.
 0. 1. 0. 0. 0. 1. 1. 0. 1. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1.
 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 1.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 1. 1. 0. 0. 1. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0.
 1. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0.
 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.
 0. 1. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1.
 0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0.
 0. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 1. 1. 1. 0. 0.
 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1.
 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 0. 0. 0. 0. 1. 1. 1. 1. 0. 0.
 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 