# Treinamento

### Carregando Arquivo de Treinamento (.csv)

In [ ]:
import pandas as pd
# Carregando dados do arquivo CSV
url = 'https://raw.githubusercontent.com/rafastos/atividadesIA/refs/heads/main/diabetes_treinamento.csv'
base_Treinamento = pd.read_csv(url,sep=',', encoding = 'latin1').values
print("--------------------------------------------------------")
print("Dados dos Pacientes - TREINAMENTO - Dimensão ", base_Treinamento.shape)
print("--------------------------------------------------------")
print(base_Treinamento)
print("---------------------------------")

# Extração dos Atributos a serem utilizadas pela rede
print("Atributos de Entrada")
print("---------------------------------")
print(base_Treinamento[:, 0:8])

print("----------------------------")
print("Classificação Supervisionada")
print("----------------------------")
print(base_Treinamento[:, -1])

--------------------------------------------------------
Dados dos Pacientes - TREINAMENTO - Dimensão  (208, 9)
--------------------------------------------------------
[[6.000e+00 1.480e+02 7.200e+01 ... 6.270e-01 5.000e+01 1.000e+00]
 [1.000e+00 8.500e+01 6.600e+01 ... 3.510e-01 3.100e+01 0.000e+00]
 [8.000e+00 1.830e+02 6.400e+01 ... 6.720e-01 3.200e+01 1.000e+00]
 ...
 [4.000e+00 1.970e+02 7.000e+01 ... 2.329e+00 3.100e+01 0.000e+00]
 [0.000e+00 1.170e+02 8.000e+01 ... 8.900e-02 2.400e+01 0.000e+00]
 [4.000e+00 1.420e+02 8.600e+01 ... 6.450e-01 2.200e+01 1.000e+00]]
---------------------------------
Atributos de Entrada
---------------------------------
[[6.000e+00 1.480e+02 7.200e+01 ... 3.360e+01 6.270e-01 5.000e+01]
 [1.000e+00 8.500e+01 6.600e+01 ... 2.660e+01 3.510e-01 3.100e+01]
 [8.000e+00 1.830e+02 6.400e+01 ... 2.330e+01 6.720e-01 3.200e+01]
 ...
 [4.000e+00 1.970e+02 7.000e+01 ... 3.670e+01 2.329e+00 3.100e+01]
 [0.000e+00 1.170e+02 8.000e+01 ... 4.520e+01 8.900e-02 2.400

### Pré-processamento de Dados

In [ ]:
from sklearn import preprocessing

# Normalizar
norm = preprocessing.Normalizer()
atributos_norm = norm.fit_transform(base_Treinamento[:, 0:8])

print("--------------------------------")
print("Atributos de Entrada - Numéricos")
print("--------------------------------")
print(atributos_norm)

classes = base_Treinamento[:, 8]
print("----------------------------------------")
print("Classificação Supervisionada - Numéricos")
print("----------------------------------------")
print(classes)

--------------------------------
Atributos de Entrada - Numéricos
--------------------------------
[[3.35523701e-02 8.27625129e-01 4.02628441e-01 ... 1.87893272e-01
  3.50622267e-03 2.79603084e-01]
 [8.42400400e-03 7.16040340e-01 5.55984264e-01 ... 2.24078506e-01
  2.95682540e-03 2.61144124e-01]
 [4.03976822e-02 9.24096981e-01 3.23181458e-01 ... 1.17658249e-01
  3.39340531e-03 1.61590729e-01]
 ...
 [5.15927076e-03 2.54094085e-01 9.02872382e-02 ... 4.73363092e-02
  3.00398540e-03 3.99843484e-02]
 [0.00000000e+00 7.19023161e-01 4.91639768e-01 ... 2.77776469e-01
  5.46949242e-04 1.47491930e-01]
 [2.30953904e-02 8.19886358e-01 4.96550893e-01 ... 2.54049294e-01
  3.72413170e-03 1.27024647e-01]]
----------------------------------------
Classificação Supervisionada - Numéricos
----------------------------------------
[1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1.
 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 1. 0. 0.
 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0

### Treinamento do KNN (K-Nearest Neighbor)

In [17]:
from sklearn.neighbors import KNeighborsClassifier
# Treinamento do Knn a partir dos atributos de entrada e classificações com K=3
modelo = KNeighborsClassifier(n_neighbors = 3)
modelo.fit(atributos_norm, classes)

# Acurácia do modelo, que é : 1 - (predições erradas / total de predições)
# Acurácia do modelo: indica uma performance geral do modelo.
# Dentre todas as classificações, quantas o modelo classificou corretamente;
# (VP+VN)/N
print('Acurácia: %.3f' % modelo.score(atributos_norm, classes))

Acurácia: 0.779


### ----------------------------------------------------------------------------

# Validação do Aprendizado

### Predição Simples

In [18]:
# Dados para teste
dados_linha769 = [[1,93,70,31,0,30.4,0.315,23]]
dados_linha677 = [[6,195,70,0,0,30.9,0.328,31]]

# Normalizar e predizer
linha769 = norm.transform(dados_linha769)
print("Linha 769", modelo.predict(linha769), "Esperado: 0")

linha677 = norm.transform(dados_linha677)
print("Linha 677", modelo.predict(linha677), "Esperado: 1")

Linha 769 [0.] Esperado: 0
Linha 677 [0.] Esperado: 1


### Predição a partir de base de dados (.csv)

In [25]:
import pandas as pd
# Carregando dados do arquivo CSV
url = 'https://raw.githubusercontent.com/rafastos/atividadesIA/refs/heads/main/diabetes.csv'
dados_df = pd.read_csv(url,sep=',', encoding = 'latin1')
base_Testes = dados_df.values
print("----------------------------")
print("Dados dos Pacientes - TESTES")
print("----------------------------")
print(base_Testes)
print("---------------------------------")

# Extração dos Atributos a serem utilizadas pela rede
print("Atributos de Entrada")
print("---------------------------------")
print(base_Testes[:, 0:8])

----------------------------
Dados dos Pacientes - TESTES
----------------------------
[[  6.    148.     72.    ...   0.627  50.      1.   ]
 [  1.     85.     66.    ...   0.351  31.      0.   ]
 [  8.    183.     64.    ...   0.672  32.      1.   ]
 ...
 [  5.    121.     72.    ...   0.245  30.      0.   ]
 [  1.    126.     60.    ...   0.349  47.      1.   ]
 [  1.     93.     70.    ...   0.315  23.      0.   ]]
---------------------------------
Atributos de Entrada
---------------------------------
[[  6.    148.     72.    ...  33.6     0.627  50.   ]
 [  1.     85.     66.    ...  26.6     0.351  31.   ]
 [  8.    183.     64.    ...  23.3     0.672  32.   ]
 ...
 [  5.    121.     72.    ...  26.2     0.245  30.   ]
 [  1.    126.     60.    ...  30.1     0.349  47.   ]
 [  1.     93.     70.    ...  30.4     0.315  23.   ]]


### Pré-processamento de Dados

In [26]:
atributos_norm = norm.transform(base_Testes[:, 0:8])

print("--------------------------------")
print("Atributos de Entrada - Numéricos")
print("--------------------------------")
print(atributos_norm)

--------------------------------
Atributos de Entrada - Numéricos
--------------------------------
[[0.03355237 0.82762513 0.40262844 ... 0.18789327 0.00350622 0.27960308]
 [0.008424   0.71604034 0.55598426 ... 0.22407851 0.00295683 0.26114412]
 [0.04039768 0.92409698 0.32318146 ... 0.11765825 0.00339341 0.16159073]
 ...
 [0.02691539 0.65135243 0.38758161 ... 0.14103664 0.00131885 0.16149234]
 [0.00665306 0.83828547 0.39918356 ... 0.20025708 0.00232192 0.31269379]
 [0.00791454 0.73605211 0.55401772 ... 0.24060198 0.00249308 0.18203439]]


### Predição da Base

In [27]:
base_Predicao = modelo.predict((atributos_norm))
print("Classificações: ", base_Predicao)

Classificações:  [1. 0. 0. 0. 1. 0. 1. 1. 1. 0. 0. 1. 1. 1. 1. 0. 1. 1. 0. 1. 0. 0. 1. 0.
 1. 1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 1. 0.
 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0.
 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 1. 0. 0. 1. 0. 0. 0. 0. 0.
 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 1. 1. 1. 1. 0. 1. 0. 0. 0. 1. 1. 0. 0. 1.
 1. 0. 0. 0. 1. 0. 0. 1. 0. 1. 1. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1.
 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 1. 1. 1. 1. 0. 0. 0. 0. 1.
 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 1. 0. 1. 1.
 1. 0. 1. 1. 1. 1. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0.
 0. 0. 1. 1. 0. 1. 1. 1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 1.
 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 1. 1. 1.
 1. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 1. 0.
 1. 1. 0. 1. 0. 1. 0. 1. 1. 0. 0. 

### Retorno aos valores Categóricos

In [29]:
import numpy as np

atributos_com_predicao = np.column_stack((base_Testes[:, 0:8], base_Predicao))
print("--------------------------------")
print("Atributos de Entrada - Numéricos")
print("--------------------------------")
print(atributos_com_predicao)


--------------------------------
Atributos de Entrada - Numéricos
--------------------------------
[[  6.    148.     72.    ...   0.627  50.      1.   ]
 [  1.     85.     66.    ...   0.351  31.      0.   ]
 [  8.    183.     64.    ...   0.672  32.      0.   ]
 ...
 [  5.    121.     72.    ...   0.245  30.      0.   ]
 [  1.    126.     60.    ...   0.349  47.      1.   ]
 [  1.     93.     70.    ...   0.315  23.      0.   ]]


In [ ]:
print("RESULTADO FINAL EM FORMATO TABULAR")
print("="*50)
colunas_finais = dados_df.columns.tolist()[:-1] + ["Predição"]
resultado_df = pd.DataFrame(atributos_com_predicao, columns=colunas_finais)
print(resultado_df.head(10))

RESULTADO FINAL EM FORMATO TABULAR
   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0          6.0    148.0           72.0           35.0      0.0  33.6   
1          1.0     85.0           66.0           29.0      0.0  26.6   
2          8.0    183.0           64.0            0.0      0.0  23.3   
3          1.0     89.0           66.0           23.0     94.0  28.1   
4          0.0    137.0           40.0           35.0    168.0  43.1   
5          5.0    116.0           74.0            0.0      0.0  25.6   
6          3.0     78.0           50.0           32.0     88.0  31.0   
7         10.0    115.0            0.0            0.0      0.0  35.3   
8          2.0    197.0           70.0           45.0    543.0  30.5   
9          8.0    125.0           96.0            0.0      0.0   0.0   

   DiabetesPedigreeFunction   Age  Predição  
0                     0.627  50.0       1.0  
1                     0.351  31.0       0.0  
2                     0.672  32.0 